language: dart
rvm:
  stable

cache:
  pub-get

os:
 linux

befor_install:  
  - sudo apt-get install -y lcov 

after_success:
  - pub run test_coverage
  - genhtml -o coverage coverage/lcov.info 
  - xdg-open coverage/index.html
