language: dart
rvm:
  stable
  
os:
 linux

cache:
  directories:
    - $HOME/.pub-cache

sudo: false

addons:
  apt:
    packages:
      - lcov

branches:
  except:
    - /^untagged/

after_success:
  - pub run test_coverage
  - genhtml -o coverage coverage/lcov.info 
  

deploy:
  provider: pages  
  skip_cleanup: true
  local_dir: coverage/
  github_token: $GITHUB_TOKEN
  on:
    branch: master
    


   
  

