language: dart
rvm:
  stable
  
os:
 linux

sudo: false

addons:
  apt:
    packages:
      - lcov
      

after_success:
  - pub run test_coverage
  - genhtml -o coverage coverage/lcov.info 
  

deploy:
  provider: releases
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  file: coverage/index.html
  keep_history: true
  on:
    branches: master

cache:
  directories:
    - $HOME/.pub-cache
    - $HOME/.packages
  

