language: dart
rvm:
  stable

cache:
  - pub-get
  
os:
 linux

addons:
  apt:
    packages:
      - lcov
      - lynx

after_success:
  - pub run test_coverage
  - genhtml -o coverage coverage/lcov.info 
  - lynx -dump coverage/index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 6e9a22ae19e7245910f4dadc3c20ce7f5589879e
  keep_history: true
  on:
    branch: master
