language: dart
rvm:
  stable
  
os:
 linux

sudo: false

addons:
  apt:
    packages:
      - lcov
      

after_success:
  - pub run test_coverage
  - genhtml -o coverage coverage/lcov.info 
  

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master

cache:
  - pub get

