language: dart
rvm:
  stable

cache:
  - worker_info
  - pub-get
  - system_info
os:
 linux

addons:
  apt:
    packages:
      - lcov
      - lynx
      - firefox

after_success:
  - pub run test_coverage
  - genhtml -o coverage coverage/lcov.info 
  - firefox coverage/index.html
  - lynx -dump coverage/index.html
