language: dart
rvm:
  stable

os:
 linux

befor_install:
  
  -sudo apt-get install -y lcov 

dart_task:
  dartanalyzer
  dartfmt

after_success:
 
  -genhtml -o coverage coverage/lcov.info 
  -open coverage/index.html
