language: dart
rvm:
  stable
  
os:
 linux

cache:
  directories:
    - $HOME/.pub-cache

sudo: false

addons:
  apt:
    packages:
      - lcov

branches:
  except:
    - /^untagged/

after_success:
  - pub run test_coverage
  - genhtml -o coverage coverage/lcov.info 
  

deploy:
  provider: releases  
  api:key: $GITHUB_TOKEN
  file:  coverage/.  
  skip_cleanup: true
  on:
    tags: false
    


   
  

